# configs/classic_control/Pendulum-v1.yaml

env: Pendulum-v1

algorithms:
  #- reinforce
  #- minibatch
  #- ars
  #- a2c
  - ddpg
  #- ppo
  - sac
  - td3
  - tqc
  #- trpo

lr: 0.001
gamma: 0.99

episodes: 50     # Only relevant for episodic algorithms like REINFORCE
timesteps: 50000   # Total timesteps for continuous algorithms (SB3-based)
batch_size: 64  # Batch size for minibatch algorithms (e.g., minibatch REINFORCE, A2C, PPO)

seeds:
  - 0
  - 1

eval_episodes: 10  # Number of episodes to evaluate each model  

eval_freq: 100  # Frequency of evaluation during training